#
# Makefile --Build rules for the package directory of makeshift.
#
MK_SRC = aip.mk deb.mk rpm.mk rpm-repo.mk zip.mk
subdir	= package

include makeshift.mk

install: install-mk
uninstall: uninstall-mk
