#
# Makefile --Build rules for the lang directory of makeshift.
#
MK_SRC = asciidoc.mk c++-library.mk c-library.mk cmd.mk c++.mk \
    c.mk conf.mk cron.mk cs.mk css.mk elisp.mk img.mk java.mk \
    javascript.mk lex-library.mk lex.mk markdown.mk md.mk mk.mk \
    nroff.mk perl.mk php.mk plantuml.mk protobuf-library.mk \
    protobuf.mk python.mk qt-library.mk qt.mk ruby.mk \
    sh.mk sql.mk tex.mk xml.mk xsd-library.mk vsproj.mk xsd.mk \
    xsl.mk yacc-library.mk yacc.mk
subdir	= lang

include makeshift.mk

install:		install-mk
uninstall:		uninstall-mk

